// <auto-generated />
using System;
using GoldenBarbers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoldenBarbers.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260212072312_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoldenBarbers.Models.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BarberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("Timeslot")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("GoldenBarbers.Models.Entities.Barber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Portrait")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Barbers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dfe81b2e-4310-4f31-ad0b-ace635786aef"),
                            Description = "Multitalented barber.",
                            Name = "John Smith",
                            Portrait = "/images/John_headshot.jpg",
                            Position = "Senior Hairdresser"
                        },
                        new
                        {
                            Id = new Guid("fe04ae76-45e3-4b91-98f3-0eae566f5850"),
                            Description = "Astute eye for beauty and elegance.",
                            Name = "Rebecca Anderson",
                            Portrait = "/images/Rebecca_headshot.jpg",
                            Position = "Senior Hairdresser"
                        },
                        new
                        {
                            Id = new Guid("db70dad6-650f-48ec-9867-66019827b11d"),
                            Description = "Style is not optional.",
                            Name = "Charles Jackson",
                            Portrait = "/images/Charles_headshot.jpg",
                            Position = "Junior Hairdresser"
                        },
                        new
                        {
                            Id = new Guid("8da88ae7-30a0-46d2-bd0e-3c33fff09fa0"),
                            Description = "Hair makes my day.",
                            Name = "Sarah Jones",
                            Portrait = "/images/Sarah_headshot.jpg",
                            Position = "Junior Hairdresser"
                        },
                        new
                        {
                            Id = new Guid("55cd3319-dbf0-40fd-84f9-6c7d6ff08305"),
                            Description = "Hallelujah!",
                            Name = "Hannah Lawson",
                            Portrait = "/images/Hannah_headshot.jpg",
                            Position = "Junior Hairdresser"
                        },
                        new
                        {
                            Id = new Guid("2fecf3a8-0b1b-464d-9603-288fd86ccd13"),
                            Description = "An up-and-coming talent in the beauty industry.",
                            Name = "Steve Robertson",
                            Portrait = "/images/Steve_headshot.jpg",
                            Position = "Trainee Hairdresser"
                        });
                });

            modelBuilder.Entity("GoldenBarbers.Models.Entities.Offering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Rate")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Offerings");
                });

            modelBuilder.Entity("GoldenBarbers.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
