// <auto-generated />
using System;
using GoldenBarbers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoldenBarbers.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260217071836_ChangeOfferingsAndCarouselSeedContent")]
    partial class ChangeOfferingsAndCarouselSeedContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppointmentOffering", b =>
                {
                    b.Property<Guid>("AppointmentsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OfferingsId")
                        .HasColumnType("uuid");

                    b.HasKey("AppointmentsId", "OfferingsId");

                    b.HasIndex("OfferingsId");

                    b.ToTable("AppointmentOffering");
                });

            modelBuilder.Entity("GoldenBarbers.Models.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BarberId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("Timeslot")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("GoldenBarbers.Models.Entities.Barber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Portrait")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Barbers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dfe81b2e-4310-4f31-ad0b-ace635786aef"),
                            Description = "Multitalented barber.",
                            Name = "John Smith",
                            Portrait = "/images/John_headshot.jpg",
                            Position = "Senior Hairdresser"
                        },
                        new
                        {
                            Id = new Guid("fe04ae76-45e3-4b91-98f3-0eae566f5850"),
                            Description = "Astute eye for beauty and elegance.",
                            Name = "Rebecca Anderson",
                            Portrait = "/images/Rebecca_headshot.jpg",
                            Position = "Senior Hairdresser"
                        },
                        new
                        {
                            Id = new Guid("db70dad6-650f-48ec-9867-66019827b11d"),
                            Description = "Style is not optional.",
                            Name = "Charles Jackson",
                            Portrait = "/images/Charles_headshot.jpg",
                            Position = "Junior Hairdresser"
                        },
                        new
                        {
                            Id = new Guid("8da88ae7-30a0-46d2-bd0e-3c33fff09fa0"),
                            Description = "Hair makes my day.",
                            Name = "Sarah Jones",
                            Portrait = "/images/Sarah_headshot.jpg",
                            Position = "Junior Hairdresser"
                        },
                        new
                        {
                            Id = new Guid("55cd3319-dbf0-40fd-84f9-6c7d6ff08305"),
                            Description = "Hallelujah!",
                            Name = "Hannah Lawson",
                            Portrait = "/images/Hannah_headshot.jpg",
                            Position = "Junior Hairdresser"
                        },
                        new
                        {
                            Id = new Guid("2fecf3a8-0b1b-464d-9603-288fd86ccd13"),
                            Description = "An up-and-coming talent in the beauty industry.",
                            Name = "Steve Robertson",
                            Portrait = "/images/Steve_headshot.jpg",
                            Position = "Trainee Hairdresser"
                        });
                });

            modelBuilder.Entity("GoldenBarbers.Models.Entities.Carousel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CarouselItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14c09ff8-c38f-4d7e-9e27-7e498f4a446d"),
                            Image = "/images/barbershop_photo1.png",
                            Name = "Haircuts & Styling"
                        },
                        new
                        {
                            Id = new Guid("dad920d2-466b-4459-95ea-94a16693d66b"),
                            Image = "/images/barbershop_photo2.png",
                            Name = "Professional Beard Trimming"
                        },
                        new
                        {
                            Id = new Guid("88f713d6-b493-4e7c-8df2-a9bbe28ef472"),
                            Image = "/images/barbershop_photo3.png",
                            Name = "Beard Styling & Treatment"
                        });
                });

            modelBuilder.Entity("GoldenBarbers.Models.Entities.Offering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JuniorPrice")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeniorPrice")
                        .HasColumnType("integer");

                    b.Property<int>("TraineePrice")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Offerings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39cb2981-ab90-4971-a4aa-f22d5a7b0a9f"),
                            Description = "Classic professional barber haircut.",
                            JuniorPrice = 30,
                            Name = "Barber Haircut",
                            SeniorPrice = 38,
                            TraineePrice = 22
                        },
                        new
                        {
                            Id = new Guid("55583c0e-9d27-4af5-af9d-1508bd3e3e3f"),
                            Description = "Haircut with a complete beard treatment package including steaming and grooming",
                            JuniorPrice = 45,
                            Name = "Haircut & Beard Treatment",
                            SeniorPrice = 50,
                            TraineePrice = 37
                        },
                        new
                        {
                            Id = new Guid("353a0efa-a853-4393-819f-fe36f771cf3b"),
                            Description = "The old-school treatment for a dutch beard style including finishing beard treatment with oils.",
                            JuniorPrice = 30,
                            Name = "Dutch Beard Treatment",
                            SeniorPrice = 35,
                            TraineePrice = 25
                        },
                        new
                        {
                            Id = new Guid("e7efb624-fa78-4bd5-9c29-cb710e32d0cc"),
                            Description = "Classic american beard trimming with razorblade and foaming.",
                            JuniorPrice = 25,
                            Name = "American Beard Trim",
                            SeniorPrice = 30,
                            TraineePrice = 22
                        });
                });

            modelBuilder.Entity("GoldenBarbers.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AppointmentOffering", b =>
                {
                    b.HasOne("GoldenBarbers.Models.Entities.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoldenBarbers.Models.Entities.Offering", null)
                        .WithMany()
                        .HasForeignKey("OfferingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
