// <auto-generated />
using System;
using GoldenBarbers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoldenBarbers.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402052135_UpdateMoreSeedData")]
    partial class UpdateMoreSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("AppointmentOffering", b =>
                {
                    b.Property<Guid>("AppointmentsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OfferingsId")
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentsId", "OfferingsId");

                    b.HasIndex("OfferingsId");

                    b.ToTable("AppointmentOffering");
                });

            modelBuilder.Entity("GoldenBarbers.Models.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BarberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BarberName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BarberPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OfferingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfferingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("GoldenBarbers.Models.Entities.Barber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Portrait")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Barbers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dfe81b2e-4310-4f31-ad0b-ace635786aef"),
                            Description = "Johnilla on yli vuosikymmenen kokemus parturituolilla, ja hän on erikoistunut tarkkoihin häivytyksiin sekä klassisiin herrasmiesleikauksiin. Hänen huolellisuutensa ja rauhallinen työskentelytapansa tekevät jokaisesta käynnistä rennon ja ammattimaisen. Halusitpa sitten terävän modernin tyylin tai ajattoman ilmeen, John varmistaa, että lähdet liikkeestä itsevarmana.",
                            Name = "John Smith",
                            PersonalAddress = "Mechelininkatu 23, Helsinki",
                            PersonalEmail = "john.s3@gmail.com",
                            PersonalPhone = "045 4318 8088",
                            Portrait = "/images/John_headshot.jpg",
                            PositionId = 1,
                            PositionName = "Senior Barber",
                            Salary = 2670.9m,
                            StartDate = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("fe04ae76-45e3-4b91-98f3-0eae566f5850"),
                            Description = "Rebeccalla on luontainen kyky ymmärtää, mikä sopii kunkin asiakkaan kasvojen muotoon ja persoonallisuuteen. Hän on erikoistunut moderneihin leikkauksiin, teksturoituihin tyyleihin ja huolelliseen viimeistelyyn. Hänen lämmin ja vastaanottavainen otteensa tekee jokaisesta käynnistä mukavan ja yksilöllisen.",
                            Name = "Rebecca Anderson",
                            PersonalAddress = "Hämeentie 47, Helsinki",
                            PersonalEmail = "rebeccaa12@gmail.com",
                            PersonalPhone = "044 1834 6640",
                            Portrait = "/images/Rebecca_headshot.jpg",
                            PositionId = 1,
                            PositionName = "Senior Barber",
                            Salary = 2530.7m,
                            StartDate = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("db70dad6-650f-48ec-9867-66019827b11d"),
                            Description = "Charles tunnetaan tarkasta tyylisilmästään ja huolellisesti muotoilemistaan parroista. Intohimollaan perinteisiä parturitekniikoita ja moderneja trendejä kohtaan hän yhdistää näiden parhaat puolet. Asiakkaat arvostavat hänen ystävällistä luonnettaan ja omistautumistaan jokaisen yksityiskohdan viimeistelyyn.",
                            Name = "Charles Jackson",
                            PersonalAddress = "Lauttasaarentie 12, Helsinki",
                            PersonalEmail = "charliejack@gmail.com",
                            PersonalPhone = "050 4871 9510",
                            Portrait = "/images/Charles_headshot.jpg",
                            PositionId = 1,
                            PositionName = "Senior Barber",
                            Salary = 2450.4m,
                            StartDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8da88ae7-30a0-46d2-bd0e-3c33fff09fa0"),
                            Description = "Sarah tunnetaan vakaasta kädestään ja virheettömästä viimeistelytyöstään. Terävistä skin fade -häivytyksistä täydellisesti muotoiltuihin partoihin – hän lähestyy jokaista leikkausta keskittyneesti ja huolella. Asiakkaat arvostavat hänen ammattimaisuuttaan ja kykyään toteuttaa heidän visionsa. Hän uskoo, että erinomainen grooming perustuu tarkkuuteen ja johdonmukaisuuteen.",
                            Name = "Sarah Jones",
                            PersonalAddress = "Fredrikinkatu 38, Helsinki",
                            PersonalEmail = "sarahlee@hotmail.com",
                            PersonalPhone = "045 7592 3593",
                            Portrait = "/images/Sarah_headshot.jpg",
                            PositionId = 2,
                            PositionName = "Junior Barber",
                            Salary = 2350.8m,
                            StartDate = new DateTime(2025, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55cd3319-dbf0-40fd-84f9-6c7d6ff08305"),
                            Description = "Hannah yhdistää luovuuden ja teknisen taidon tuottaakseen erinomaisia tuloksia. Hän nauttii työskentelystä sekä klassisten tyylien että rohkeiden modernien ilmeiden parissa, räätälöiden jokaisen leikkauksen yksilöllisesti. Hänen ystävällinen asenteensa ja tarkkuutensa tekevät hänestä asiakkaiden suosikin.",
                            Name = "Hannah Lawson",
                            PersonalAddress = "Sturenkatu 61, Helsinki",
                            PersonalEmail = "hannah.law@gmail.com",
                            PersonalPhone = "050 6859 4772",
                            Portrait = "/images/Hannah_headshot.jpg",
                            PositionId = 2,
                            PositionName = "Junior Barber",
                            Salary = 2290.5m,
                            StartDate = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2fecf3a8-0b1b-464d-9603-288fd86ccd13"),
                            Description = "Steve on lahjakas harjoittelijamme, joka tuo mukanaan tuoretta energiaa ja vahvan halun kehittyä alan ammattilaiseksi. Hän hioo taitojaan parhaillaan senioritiimimme ohjauksessa keskittyen siisteihin leikkauksiin ja tarkkoihin tyyleihin. Steve on yksityiskohtiin paneutuva, kärsivällinen ja sitoutunut jatkuvaan kehittymiseen.",
                            Name = "Steve Robertson",
                            PersonalAddress = "Itämerenkatu 5, Helsinki",
                            PersonalEmail = "stevie_robs@gmail.com",
                            PersonalPhone = "045 5627 5582",
                            Portrait = "/images/Steve_headshot.jpg",
                            PositionId = 3,
                            PositionName = "Trainee Barber",
                            Salary = 2020.3m,
                            StartDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GoldenBarbers.Models.Entities.Carousel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CarouselItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14c09ff8-c38f-4d7e-9e27-7e498f4a446d"),
                            Image = "/images/barbershop_photo1.png",
                            Name = "Hiustenleikkaukset & Stailaukset"
                        },
                        new
                        {
                            Id = new Guid("dad920d2-466b-4459-95ea-94a16693d66b"),
                            Image = "/images/barbershop_photo2.png",
                            Name = "Ammattimainen parran trimmaus"
                        },
                        new
                        {
                            Id = new Guid("88f713d6-b493-4e7c-8df2-a9bbe28ef472"),
                            Image = "/images/barbershop_photo3.png",
                            Name = "Parran stailaus & Hoito"
                        });
                });

            modelBuilder.Entity("GoldenBarbers.Models.Entities.Offering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JuniorPrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeniorPrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TraineePrice")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Offerings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39cb2981-ab90-4971-a4aa-f22d5a7b0a9f"),
                            Description = "Klassinen korkealaatuinen parturileikkaus",
                            Icon = "/images/barber_haircut.png",
                            JuniorPrice = 30,
                            Name = "Parturileikkaus",
                            SeniorPrice = 38,
                            TraineePrice = 22
                        },
                        new
                        {
                            Id = new Guid("55583c0e-9d27-4af5-af9d-1508bd3e3e3f"),
                            Description = "Hiustenleikkaus täydellisellä parran hoitopaketilla, sisältää höyrytyksen ja siistimisen",
                            Icon = "/images/haircut_beard_treatment.png",
                            JuniorPrice = 45,
                            Name = "Hiustenleikkaus & Parran hoito",
                            SeniorPrice = 50,
                            TraineePrice = 37
                        },
                        new
                        {
                            Id = new Guid("353a0efa-a853-4393-819f-fe36f771cf3b"),
                            Description = "Vanhan koulun hoitopaketti hollantilaisen partatyylin mukaan sisältäen hoitoviimeistelyn öljyillä",
                            Icon = "/images/dutch_beard_treatment.png",
                            JuniorPrice = 30,
                            Name = "Hollantilainen partahoito",
                            SeniorPrice = 35,
                            TraineePrice = 25
                        },
                        new
                        {
                            Id = new Guid("e7efb624-fa78-4bd5-9c29-cb710e32d0cc"),
                            Description = "Klassinen amerikkalainen parran trimmaus partaterällä ja vaahdotuksella",
                            Icon = "/images/american_beard_trim.png",
                            JuniorPrice = 25,
                            Name = "Amerikkalainen parran trimmaus",
                            SeniorPrice = 28,
                            TraineePrice = 23
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AppointmentOffering", b =>
                {
                    b.HasOne("GoldenBarbers.Models.Entities.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoldenBarbers.Models.Entities.Offering", null)
                        .WithMany()
                        .HasForeignKey("OfferingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
